### PR TITLE
Bash cat syntax TIL from @isislovecruft

### PR DESCRIPTION
**Pull request by BenGitsCode**
- Cat and it's many possible signatures.

### CODE REVIEW

**Comment by laurpaik-zz** [comment]
you left a random tic mark Line 3 but otherwise looks good

**Review by laurpaik-zz — APPROVED** [review]

**Review by laurpaik-zz — COMMENTED** [review]
What's the tic mark for on line 3? I can't stop looking at it haha.

Also, typo on line 18: `shoveld` should be `shoveled`

**Comment by BenGitsCode** [comment]
Corrected the typo so it should be good now, good catch!

**Comment by laurpaik-zz** [comment]
Wait @BenGitsCode it's a matter of 
- "which **shoveled** the contents of the til-template into a new file called cat-madness." 
vs 
- "which **should** the contents of the til-template into a new file called cat-madness." 
And I think you want the former, but you changed it to the latter?

**Comment by BenGitsCode** [comment]
🤦‍♂️  You're totally right, I misread that comment as changing it to should so I did that, but you're right, it's just that shoveled is misspelled. This one will actually finish it 🤣

**Pull request merged**
